In [5]:
import pandas as pd

import numpy as np
import random

from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import metrics

import matplotlib.pyplot as plt

df2 = pd.read_csv("Biomechanical_Data_2Classes.csv")
df2_features = df2.drop(["class"], axis = 1)
df2_class =df2["class"]

df2_xtrain, df2_xtest, df2_ytrain, df2_ytest = train_test_split(df2_features, df2_class, test_size = 80, random_state = 0)

clf_list = []
df2_ypred_list = []
accu_list = []
i = 0
for min_per_leaf in [5, 15, 25, 40, 50]:
    clf_list.append(tree.DecisionTreeClassifier(min_samples_leaf= min_per_leaf))
    clf_list[i].fit(df2_xtrain, df2_ytrain)
    df2_ypred_list.append(clf_list[i].predict(df2_xtest))
    accu_list.append(metrics.accuracy_score(df2_ytest, df2_ypred_list[i]))
    i += 1

#tree.plot_tree(clf_list[4])
"""
plt.plot([5,15,25,40,50], accu_list, "bs", label = "accuracy")
plt.ylabel("accuracy score")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "upper right")
plt.show"""

p_r_f_normal = []
for i in range(0, 5):
    p_r_f_normal.append(metrics.precision_recall_fscore_support(df2_ytest, df2_ypred_list[i], average=None, labels=["Normal"]))

p_r_f_abnormal = []
for i in range(0, 5):
    p_r_f_abnormal.append(metrics.precision_recall_fscore_support(df2_ytest, df2_ypred_list[i], average=None, labels=["Abnormal"]))

p_normal = []
for i in range(0, 5):
    p_normal.append(p_r_f_normal[i][0][0])

p_abnormal = []
for i in range(0, 5):
    p_abnormal.append(p_r_f_abnormal[i][0][0])

r_normal = []
for i in range(0, 5):
    r_normal.append(p_r_f_normal[i][1][0])

r_abnormal = []
for i in range(0, 5):
    r_abnormal.append(p_r_f_abnormal[i][1][0])
"""
plt.plot([5,15,25,40,50], p_normal, "bs",label = "normal")
plt.plot([5,15,25,40,50], p_abnormal, "g^", label = "abnormal")
plt.ylabel("precision")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "right")
plt.show
"""
"""
plt.plot([5,15,25,40,50], r_normal, "bs",label = "normal")
plt.plot([5,15,25,40,50], r_abnormal, "g^", label = "abnormal")
plt.ylabel("recall")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "right")
plt.show"""


'\nplt.plot([5,15,25,40,50], r_normal, "bs",label = "normal")\nplt.plot([5,15,25,40,50], r_abnormal, "g^", label = "abnormal")\nplt.ylabel("recall")\nplt.xlabel("min_sample_per_leaf")\nplt.legend(loc = "right")\nplt.show'

In [6]:
df3 = pd.read_csv("Biomechanical_Data_3Classes.csv")
df3_features = df3.drop(["class"], axis = 1)
df3_class =df3["class"]

df3_xtrain, df3_xtest, df3_ytrain, df3_ytest = train_test_split(df3_features, df3_class, test_size = 80, random_state = 0)

clf3_list = []
df3_ypred_list = []
accu_list = []
i = 0
for min_per_leaf in [5, 15, 25, 40, 50]:
    clf3_list.append(tree.DecisionTreeClassifier(min_samples_leaf= min_per_leaf))
    clf3_list[i].fit(df3_xtrain, df3_ytrain)
    df3_ypred_list.append(clf3_list[i].predict(df3_xtest))
    accu_list.append(metrics.accuracy_score(df3_ytest, df3_ypred_list[i]))
    i += 1
#tree.plot_tree(clf3_list[4])
"""
plt.plot([5,15,25,40,50], accu_list, "bs", label = "accuracy")
plt.ylabel("accuracy score")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "upper right")
plt.show"""

p_r_f_normal = []
for i in range(0, 5):
    p_r_f_normal.append(metrics.precision_recall_fscore_support(df3_ytest, df3_ypred_list[i], average=None, labels=["Normal"]))

p_r_f_hernia = []
for i in range(0, 5):
    p_r_f_hernia.append(metrics.precision_recall_fscore_support(df3_ytest, df3_ypred_list[i], average=None, labels=["Hernia"]))

p_r_f_spondylolisthesis = []
for i in range(0, 5):
    p_r_f_spondylolisthesis.append(metrics.precision_recall_fscore_support(df3_ytest, df3_ypred_list[i], average=None, labels=["Spondylolisthesis"]))

p_normal = []
for i in range(0, 5):
    p_normal.append(p_r_f_normal[i][0][0])

p_hernia = []
for i in range(0, 5):
    p_hernia.append(p_r_f_hernia[i][0][0])

p_spondylolisthesis = []
for i in range(0, 5):
    p_spondylolisthesis.append(p_r_f_spondylolisthesis[i][0][0])

r_normal = []
for i in range(0, 5):
    r_normal.append(p_r_f_normal[i][1][0])

r_hernia = []
for i in range(0, 5):
    r_hernia.append(p_r_f_hernia[i][1][0])

r_spondylolisthesis = []
for i in range(0, 5):
    r_spondylolisthesis.append(p_r_f_spondylolisthesis[i][1][0])
"""
plt.plot([5,15,25,40,50], p_normal, "bs",label = "normal")
plt.plot([5,15,25,40,50], p_hernia, "g^", label = "hernia")
plt.plot([5,15,25,40,50], p_spondylolisthesis, "r*", label = "spondylolisthesis")
plt.ylabel("precision")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "lower left")
plt.show
"""
"""
plt.plot([5,15,25,40,50], r_normal, "bs",label = "normal")
plt.plot([5,15,25,40,50], r_hernia, "g^", label = "hernia")
plt.plot([5,15,25,40,50], r_spondylolisthesis, "r*", label = "spondylolisthesis")
plt.ylabel("recall")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "lower left")
plt.show"""

'\nplt.plot([5,15,25,40,50], r_normal, "bs",label = "normal")\nplt.plot([5,15,25,40,50], r_hernia, "g^", label = "hernia")\nplt.plot([5,15,25,40,50], r_spondylolisthesis, "r*", label = "spondylolisthesis")\nplt.ylabel("recall")\nplt.xlabel("min_sample_per_leaf")\nplt.legend(loc = "lower left")\nplt.show'

In [13]:
df2["class_n"] = [0] * 310
for i in range(0, 310):
    if df2.loc[i, "class"] == "Abnormal":
        df2.loc[i, "class_n"] = 1

df2.corr(method = "pearson")
#d_s has the highest cor
df2_features = df2.drop(["degree_spondylolisthesis", "class", "class_n"], axis = 1)
df2_class =df2["class"]

df2_xtrain, df2_xtest, df2_ytrain, df2_ytest = train_test_split(df2_features, df2_class, test_size = 80, random_state = 0)

clf_list = []
df2_ypred_list = []
accu_list = []
i = 0
for min_per_leaf in [5, 15, 25, 40, 50]:
    clf_list.append(tree.DecisionTreeClassifier(min_samples_leaf= min_per_leaf))
    clf_list[i].fit(df2_xtrain, df2_ytrain)
    df2_ypred_list.append(clf_list[i].predict(df2_xtest))
    accu_list.append(metrics.accuracy_score(df2_ytest, df2_ypred_list[i]))
    i += 1

#tree.plot_tree(clf3_list[0])
#tree.plot_tree(clf3_list[1])
#tree.plot_tree(clf3_list[2])
#tree.plot_tree(clf3_list[3])
#tree.plot_tree(clf3_list[4])

"""
plt.plot([5,15,25,40,50], accu_list, "bs", label = "accuracy")
plt.ylabel("accuracy score")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "upper right")
plt.show"""

p_r_f_normal = []
for i in range(0, 5):
    p_r_f_normal.append(metrics.precision_recall_fscore_support(df2_ytest, df2_ypred_list[i], average=None, labels=["Normal"]))


p_r_f_abnormal = []
for i in range(0, 5):
    p_r_f_abnormal.append(metrics.precision_recall_fscore_support(df2_ytest, df2_ypred_list[i], average=None, labels=["Abnormal"]))

p_normal = []
for i in range(0, 5):
    p_normal.append(p_r_f_normal[i][0][0])

p_abnormal = []
for i in range(0, 5):
    p_abnormal.append(p_r_f_abnormal[i][0][0])

r_normal = []
for i in range(0, 5):
    r_normal.append(p_r_f_normal[i][1][0])

r_abnormal = []
for i in range(0, 5):
    r_abnormal.append(p_r_f_abnormal[i][1][0])
"""
plt.plot([5,15,25,40,50], p_normal, "bs",label = "normal")
plt.plot([5,15,25,40,50], p_abnormal, "g^", label = "abnormal")
plt.ylabel("precision")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "upper right")
plt.show
"""
"""
plt.plot([5,15,25,40,50], r_normal, "bs",label = "normal")
plt.plot([5,15,25,40,50], r_abnormal, "g^", label = "abnormal")
plt.ylabel("recall")
plt.xlabel("min_sample_per_leaf")
plt.legend(loc = "right")
plt.show"""
#df2.corr(method = "pearson")
metrics.precision_recall_fscore_support(df2_ytest, df2_ypred_list[1], average=None, labels=["Normal", "Abnormal"])


(array([0.56, 0.8 ]),
 array([0.56, 0.8 ]),
 array([0.56, 0.8 ]),
 array([25, 55], dtype=int64))